repos:
  # Versioning: Commit messages & changelog
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.10
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: local
    hooks:
      - id: oxfmt
        name: oxfmt
        files: ^
        entry: bash -c 'test "$#" -gt 0 && oxfmt --write "$@" || exit 0' --
        language: node
        "types": [text]
        additional_dependencies: ["oxfmt@0.35.0"]
        args: ["!cla.json", "pnpm-lock.yaml", "!CHANGELOG.md"]

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
        args: [--fix, --ignore, CHANGELOG.md, --ignore, LICENSE.md, --ignore, docs/components]
