name: 📖 Publish Docs

on:
  push:
    paths:
      - .storybook/**
      - components/**
    branches: [main]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  build:
    uses: hotosm/gh-workflows/.github/workflows/pnpm_build.yml@main
    with:
      command: build:docs
      output_path: docs
      github_pages: true
