name: 📖 Publish Docs

on:
  push:
    paths:
      - docs/**
      - components/**
      - mkdocs.yml
    branches: [main]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  build_stories:
    uses: hotosm/gh-workflows/.github/workflows/pnpm_build.yml@2.0.1
    with:
      command: build:docs
      output_path: docs/stories

  publish_docs:
    uses: hotosm/gh-workflows/.github/workflows/mkdocs_build.yml@2.0.1
    needs: [build_stories]
    with:
      include_artifacts: true
