name: 🚀 Publish to npmjs.org

on:
  release:
    types: [published]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC NPM publish
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Publish
        run: npm publish --access=public
